name: Publish on Gradle Plugin Portal
on:
  release:
    types: [ published ]
jobs:
  run-gradle:
    runs-on: ubuntu-latest
    name: Run Gradle
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        id: publish
        env:
          GPG_SECRET_KEY: ${{secrets.GPG_SECRET_KEY}}
          GPG_SECRET_KEY_PASSWORD: ${{secrets.GPG_SECRET_KEY_PASSWORD}}
          SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
        with:
          gradle-version: wrapper
          arguments: publishToSonatype closeSonatypeStagingRepository
