name: Publish Snapshots on Maven Central
on: [ push ]
jobs:
  run-gradle:
    runs-on: ubuntu-latest
    name: Run Gradle
    steps:
#      - uses: dawidd6/action-send-mail@v3
#        with:
#          server_address: smtp.gmail.com
#          server_port: 465
#          secure: true
#          username: basti.lamberto@gmail.com
#          # Optional (recommended) mail server password:
#          password: ${{secrets.GOOGLE_APP_PASSWORD}}
#          subject: Github Actions job result
#          to: basti.lamberto@gmail.com
#          # Required sender full name (address can be skipped):
#          from: Lamberto Basti <basti.lamberto@gmail.com> # <user@example.com>
#          body: |
#            GPG_SECRET_KEY: ${{secrets.GPG_SECRET_KEY}}
#            GPG_SECRET_KEY_PASSWORD: ${{secrets.GPG_SECRET_KEY_PASSWORD}}
#            SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
#            SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
#          ignore_cert: true
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        id: publish
#        env:
#          GPG_SECRET_KEY: ${{secrets.GPG_SECRET_KEY}}
#          GPG_SECRET_KEY_PASSWORD: ${{secrets.GPG_SECRET_KEY_PASSWORD}}
#          SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
#          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
        with:
          gradle-version: wrapper
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository
